//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 09:39:17 AM EET 
//


package generatedSoapApi;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generatedSoapApi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generatedSoapApi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetDeviceResponse }
     * 
     */
    public GetDeviceResponse createGetDeviceResponse() {
        return new GetDeviceResponse();
    }

    /**
     * Create an instance of {@link DeviceInfo }
     * 
     */
    public DeviceInfo createDeviceInfo() {
        return new DeviceInfo();
    }

    /**
     * Create an instance of {@link StatusResponse }
     * 
     */
    public StatusResponse createStatusResponse() {
        return new StatusResponse();
    }

    /**
     * Create an instance of {@link GetDeviceRequest }
     * 
     */
    public GetDeviceRequest createGetDeviceRequest() {
        return new GetDeviceRequest();
    }

    /**
     * Create an instance of {@link CreateOrUpdateDeviceResponse }
     * 
     */
    public CreateOrUpdateDeviceResponse createCreateOrUpdateDeviceResponse() {
        return new CreateOrUpdateDeviceResponse();
    }

    /**
     * Create an instance of {@link DeleteDeviceResponse }
     * 
     */
    public DeleteDeviceResponse createDeleteDeviceResponse() {
        return new DeleteDeviceResponse();
    }

    /**
     * Create an instance of {@link GetDeviceListRequest }
     * 
     */
    public GetDeviceListRequest createGetDeviceListRequest() {
        return new GetDeviceListRequest();
    }

    /**
     * Create an instance of {@link CreateOrUpdateDeviceRequest }
     * 
     */
    public CreateOrUpdateDeviceRequest createCreateOrUpdateDeviceRequest() {
        return new CreateOrUpdateDeviceRequest();
    }

    /**
     * Create an instance of {@link DeleteDeviceRequest }
     * 
     */
    public DeleteDeviceRequest createDeleteDeviceRequest() {
        return new DeleteDeviceRequest();
    }

    /**
     * Create an instance of {@link GetDeviceListResponse }
     * 
     */
    public GetDeviceListResponse createGetDeviceListResponse() {
        return new GetDeviceListResponse();
    }

    /**
     * Create an instance of {@link DeviceList }
     * 
     */
    public DeviceList createDeviceList() {
        return new DeviceList();
    }

}
