//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.09 at 10:59:54 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://asm_api/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package generatedSoapApi;
